### PR TITLE
Add support for ESLint plugin Flowtype

### PR DESCRIPTION
**Pull request by leonardfactory**
Add support for using ESLint plugin to recognize [Flowtype](https://flowtype.org), [eslint-plugin-flowtype](https://github.com/gajus/eslint-plugin-flowtype).

Hope that the PR is fine, please let me know if there's some work left to do in order to include it.

### CODE REVIEW

**Comment by pbrisbin** [comment]
Thanks! I'm going to merge this in now, but wait for the similar `-angular` PR to land before releasing.

**Comment by leonardfactory** [comment]
Thanks!

**Comment by jdelStrother** [comment]
Do you have a rough timeline on that?

**Comment by wfleming** [comment]
@jdelStrother this was shipped a little while ago. It should be available now for you to use with the CLI or on codeclimate.com. If you're using the CLI, please run `codeclimate engines:install` from your project directory to make sure you have the most recent version of the engine. If you're still getting errors indicating the plugin is not being loaded, please open an issue with details. Thanks!

**Pull request merged**
