### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by leftees**
Add support for `eslint-config-angular` plugin.

### CODE REVIEW

**Comment by GordonDiggs** [comment]
Should there be a change to the shrinkwrap json file too? cc @pbrisbin

**Comment by pbrisbin** [comment]
Yes. As a process though, I think it's reasonable for the engineer to do that as part of picking this up from CX (WDYT?) -- I personally don't know how to update the shrinkwrap file :|

**Comment by pbrisbin** [comment]
@GordonDiggs updated and rebased. Added a `make` task to update the shrinkwrap using the engine image's `npm` too.

**Comment by GordonDiggs** [comment]
Nice LGTM

**Pull request merged**
