### PR TITLE
Add react-native plugin

### PR DESCRIPTION
**Pull request by afestein**
Adds the [ESLint plugin for React Native](https://www.npmjs.com/package/eslint-plugin-react-native)

### CODE REVIEW

**Comment by dblandin** [comment]
Hey @afestein,

Thanks for the PR!

Before merging, are there any category mappings to specify?

https://github.com/codeclimate/codeclimate-eslint/blob/master/lib/check_category_mapping.json

**Comment by afestein** [comment]
Thanks for the heads up @dblandin. How's that now?

**Comment by dblandin** [comment]
@afestein Looks great! Thanks!

**Comment by dblandin** [comment]
@afestein FYI: I just released an update including the plugin from this PR. Should be available via the CLI and codeclimate.com now. Let me know if you run into any issues!

**Pull request merged**
