### PR TITLE
Easier debugging

### PR DESCRIPTION
**Pull request by filipesperandio**
`make test NPM_TEST_TARGET=test.debug`

### CODE REVIEW

**Comment by filipesperandio** [comment]
@pbrisbin What your taste says?

**Comment by pbrisbin** [comment]
I might do something like this:

```make
NPM_TEST_TARGET ?= test

test:
    docker run --rm \
      --volume ... \
      --workdir ... \
      $(IMAGE_NAME) npm $(NPM_TEST_TARGET)
```

Using `--workdir` (something we didn't realize existed when this was first written) makes things a bit easier.

```console
make test NPM_TEST_TARGET=test.debug
```

**Comment by filipesperandio** [comment]
Interesting. It keeps the Makefile clean.
I was going to say that the WORKDIR is already to what we expect here, then I realize we actually have it duplicated [here](https://github.com/codeclimate/codeclimate-eslint/blob/master/Dockerfile#L34)

**Comment by pbrisbin** [comment]
Yeah, for some reason the SPEC says `WORKDIR` must be `/code`, so we set it to that at the end. We have the one at the top to make the commands in between easier.

**Pull request merged**
