### PR TITLE
Add import/no-cycle to blocklisted rules

### PR DESCRIPTION
**Pull request by gilbarbara**

### CODE REVIEW

**Comment by wilson** [comment]
Hi there. Can you elaborate a little on why we need this?
Is it because the `no-cycle` check requires that the `node_modules` directory be present?

**Comment by gilbarbara** [comment]
@wilson Hello! Yes, this rule requires static analysis that involves `node_modules`

**Comment by wilson** [comment]
This has been merged to the ESLint 3 / master world now; this same change is probably necessary on the ESLint-4 channel as well. Which channel(s) are you using?

**Comment by gilbarbara** [comment]
Cool, thanks!
I'm using `eslint-4`. Do I need to commit that change as well?

**Comment by wilson** [comment]
I just pushed it to `eslint-4` as well; I'm guessing ESLint 2.x users don't encounter this newer feature, so that channel presumably doesn't need it. Thanks!

**Pull request merged**
