### PR TITLE
Add eslint-plugin-vue-a11y plugin support

### PR DESCRIPTION
**Pull request by rv-asilva**

### CODE REVIEW

**Comment by codersbrew** [comment]
@eutopian any chance we can get this merged in?

**Comment by rv-asilva** [comment]
@filipesperandio Is there anything we can do to move this along?

**Comment by filipesperandio** [comment]
@rv-asilva Getting to this now. Sorry for the delay.
Just double checking, is this really meant for ESLint 3?
Curious why you are not using `channel/eslint-5`, any specifics?

**Comment by rv-asilva** [comment]
> @rv-asilva Getting to this now. Sorry for the delay.
> Just double checking, is this really meant for ESLint 3?
> Curious why you are not using `channel/eslint-5`, any specifics?

Not familiar with that channel branch.

**Comment by rv-asilva** [comment]
Will close and add this plugin to that channel.

**Comment by filipesperandio** [comment]
The `master` branch have ESLint on version 3. 

> Will close and add this plugin to that channel.

Cool, I will check it out right away.

**Comment by filipesperandio** [comment]
Some more details on the branches: https://docs.codeclimate.com/docs/eslint#section-eslint-versions

**Pull request closed without merging**
