### PR TITLE
feat: add badi eslint to whitelist

### PR DESCRIPTION
**Pull request by jepser**
- Badi eslint configuration

### CODE REVIEW

**Comment by jepser** [comment]
How long does it take to get the PR reviewed @ale7714 ?

**Comment by filipesperandio** [comment]
@jepser Can you elaborate on what Badi eslint brings on?

@ale7714 I am leaning towards not merging this in. The npm package in questions has only  36 downloads in total, the github link there does not exists, besides its being first released only 20 days ago.
Without any docs or even the repo, the only way to know what this does would be inspecting the source.

**Comment by jepser** [comment]
@filipesperandio thanks for answering, to give you some context:
@badi we use start using a custom eslint configuration some time ago, but since the projects have been more we decided to have a  portable configuration, @badi/eslint-config.

The team installed Codeclimate on our project and we wanted to continue using it because of the value it has to us, but since we changed to a portable (private) configuration, the eslint fails since you run linting against your repository.

The eslint-config wasn't be meant to be public but since Codeclimate doesn't have a way  to install it, from a ticket we were told to make a PR with our configuration so we needed to make it public.

So, answering your question ** Can you elaborate on what Badi eslint brings on?**
It's not about 36 downloads in total, or that it's new, but the way we were told to go in order to continue using your service with our configuration.

I do agree that it needs more docs but since it's only one file with a set of rules, the time it takes to review is trivial.

If there is another option, I'm down to collaborate.

**Comment by badi** [comment]
uhh, for the record this is not me. Did you mean `@badiapp`?

**Comment by jepser** [comment]
Yes, sorry @badi, haha I didn't check that I would tag you. @badiapp yes.

**Comment by filipesperandio** [comment]
@jepser We try to support the most common modules from the community and be flexible with the engine configuration.
Each project may have their set of configs and we don't enforce a set rules broadly.

Bringing on the @badiapp makes it broadly available, which we don't want for configuration rules, and since we can't easly inspect a private lib,
it is also risky.

I've made an example on how to configure CodeClimate to use a common eslint set of rules [here](https://github.com/filipesperandio/eslint-base-example)
that you can follow.

**Comment by jepser** [comment]
Thanks @filipesperandio. I understand your point, but I don't agree on "we don't want for configuration rules", I believe a tool that provides a solution based on a broad horizontal shouldn't be opinionated. Nor "we can't easily inspect a private lib", [@badi/eslint-config](https://www.npmjs.com/package/@badi/eslint-config) is a public project and since the code is not being transpired, it should be trivial to check the file that contains the rules.

Thanks for letting us know your decision, from here we will evaluate the viability of it and decide what are we going to do.

**Comment by filipesperandio** [comment]
@jepser It is not opinionated, it will be somehow if the module is incorporated, since your configs will be available to all clients, not only you.
We allow for any eslint configs as pointed out in the previous comment, this is just not the way we handle this kind of configs. Sorry if there was a confusion on our side to properly communicate that to start with.

**Pull request closed without merging**
