### PR TITLE
add eslint-plugin-cypress

### PR DESCRIPTION
**Pull request by efueger**
Add `eslint-plugin-cypress` to resolve issue https://github.com/codeclimate/codeclimate-eslint/issues/366

### CODE REVIEW

**Comment by efueger** [comment]
FYI: I used the instructions in the [CONTRIBUTING.md](https://github.com/codeclimate/codeclimate-eslint/blob/master/CONTRIBUTING.md) file to test locally.
- should I do the same for the `eslint-4` channel? @ale7714

**Comment by ale7714** [comment]
Thanks @efueger 💪. Max is taking over :)

**Comment by maxjacobson** [comment]
> should I do the same for the `eslint-4` channel? 

@efueger yes please. The master branch tracks eslint-3 currently, so I'll merge this in and get it onto the stable & eslint-3 channels, but we might as well bring it forward as well to eslint-4

**Comment by maxjacobson** [comment]
LMK if you hit any snags with that

**Pull request merged**
