### PR TITLE
Eslint vue 7x upgrade

### PR DESCRIPTION
**Pull request by alboyadjian**
Addresses https://github.com/codeclimate/codeclimate-eslint/issues/517

### CODE REVIEW

**Comment by alboyadjian** [comment]
cc: @fede-moya @ale7714 @mishschmid

**Review by fede-moya — APPROVED** [review]
Will be merging tomorrow morning 👍🏼

**Comment by alboyadjian** [comment]
Thanks. About how long between when it's merged and when the codeclimate platform gets updated?

**Comment by fede-moya** [comment]
@alboyadjian you can expect it to be live sometime after 6hrs, it might take longer in some cases.

**Pull request merged**
