### PR TITLE
Add eslint-plugin-vue and eslint-plugin-html

### PR DESCRIPTION
**Pull request by JiriChara**
Hey,

I tried to build my repository on codeclimate and it seems like that `eslint-plugin-vue` and `eslint-plugin-html` is missing.

I hope this PR will fix the issue.

### CODE REVIEW

**Comment by dblandin** [comment]
Hey @JiriChara ,

Thanks for the PR! Are there any category mappings to specify for these plugins?

https://github.com/codeclimate/codeclimate-eslint/blob/master/lib/check_category_mapping.json

Looks like this PR might also need a rebase.

**Comment by JiriChara** [comment]
Hey @dblandin,

I have rebased to latest greatest master, but  I am not sure if any category mappings are required. How can I find it out?

**Comment by dblandin** [comment]
If the plugins only emits `Style` issues, which is the default, then you should be all set. If the plugins check for issues of complexity, clarity, security, etc, then some mappings would be beneficial.

Here's a list of the categories that the we currently support: https://github.com/codeclimate/spec/blob/master/SPEC.md#categories

**Comment by JiriChara** [comment]
@dblandin both plugins are checking styling only right now. I think they would like to add check for unclosed tags, but it's not yet implemented.

**Comment by JiriChara** [comment]
@dblandin Do you think we can get this merged?

**Comment by dblandin** [comment]
@JiriChara FYI: I just released an update including the plugins from this PR. Should be available via the CLI and codeclimate.com now. Let me know if you run into any issues!

**Comment by JiriChara** [comment]
@dblandin works like a charm. Thanks!

**Pull request merged**
