### PR TITLE
Check yarn.lock's correctness

### PR DESCRIPTION
**Pull request by maxjacobson**
I found myself suggesting this in another PR, so I decided to just open it as its own PR https://github.com/codeclimate/codeclimate-eslint/pull/260#issuecomment-297179681

### CODE REVIEW

**Comment by maxjacobson** [comment]
Hm, maybe this won't work actually -- we need builds to pass in order for greenkeeper PRs to run the `bin/circleci-update-yarn-lock` script. Will think more about that later, but shouldn't merge this for now ⚠️

**Comment by filipesperandio** [comment]
@maxjacobson Yeah... I was giving some thought to this as well, yesterday.
I think keeping `yarn.lock` sane is a task for the developer, meaning I would rather have it on its own target or as `test` dependency instead of `citest`, WDYT?

**Comment by filipesperandio** [comment]
@maxjacobson Was looking into `bin/circleci-update-yarn-lock` and it also does `yarn check`... maybe that's good enough?

**Comment by maxjacobson** [comment]
@filipesperandio that's triggered when greenkeeper opens a PR updating `package.json`. It only runs on `greenkeeper/*` branches (https://github.com/codeclimate/codeclimate-eslint/blob/da4d8ed7ac400b4ff4066e36644de0509e5e28cf/circle.yml#L34-L37)

**Comment by filipesperandio** [comment]
Does `greenkeeper` check dependencies once a day or so? (Not too familiar with greenkeeper)

**Comment by maxjacobson** [comment]
Something like that. They make one PR per dependency package, and I think they sometimes open multiple PRs in the same day.

**Pull request closed without merging**
