### PR TITLE
Upgrade @typescript-eslint/eslint-plugin and @typescript-eslint/parser to 2.29.0 for eslint 6

### PR DESCRIPTION
**Pull request by Loremaster**
That should fix https://github.com/codeclimate/codeclimate-eslint/issues/477

### CODE REVIEW

**Comment by Loremaster** [comment]
@efueger any updates?

**Comment by efueger** [comment]
@Loremaster - thanks for checking! it's in the queue, but no update yet. 👌

**Comment by Loremaster** [comment]
@efueger bump. :) Will it be merged soon? We need those changes to be able to enable some checks in our project which are currently blocked by codeclimate.

**Comment by efueger** [comment]
Hi @Loremaster - checking with the team. Sorry for the wait!

**Comment by Loremaster** [comment]
@efueger anything I can do to speedup the review and merge?

**Comment by efueger** [comment]
thanks for the nudge! that's probably the best thing to do @Loremaster . 
- We're making some process changes for handling these, but I'll do my best to push this over the line. 👌

**Comment by peterkrieg** [comment]
hi @efueger  - wondering if there are any updates on this PR?  It would also be a big help to get this merged. Thank you!

**Comment by Loremaster** [comment]
@efueger it has been over a month since I opened the PR. When do you pan to merge it?

**Comment by marcotuna** [comment]
I know that this message adds nothing but... Are there any plans to merge this? I have my analysis failing due to this problem. It's really annoying that I can't use codeclimate because most of my projects rely on eslint with typescript validations

**Comment by peterkrieg** [comment]
@marcotuna totally understand, I'm in a similar situation.  @efueger  anything we can do to help get this released?

**Comment by efueger** [comment]
Hi @peterkrieg  - thanks for the bump! Checking with my team now. 👌

**Comment by krzysiek1507** [comment]
Any chance to release it? ;)

**Comment by rdadoune** [comment]
Any word on this? Also waiting for this to be fixed.

**Comment by efueger** [comment]
Hi all,

Good news! 
- We've just recently updated typescript-eslint [here](https://github.com/codeclimate/codeclimate-eslint/pull/489/files). 🎉

Thanks again for the nudge on this. I'll close this PR, but if you bump into anything else, let me know. Here to help.

Emily

**Comment by rdadoune** [comment]
Hey @efueger thanks for the update, can you also update `typescript`? It's currently at version 3.4.4: https://github.com/codeclimate/codeclimate-eslint/blob/640ade071d24ec5ce685e4f7a7b63bc2bb6b157a/package.json#L89 In version 3.7 they added support for [optional chaining](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining) and [nullish coalescing](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#nullish-coalescing) and we're getting parsing errors related to this. Specifically codeclimate reports "Parsing error: Expression expected." when it encounters use of these new features.

Example:
```typescript
// Optional Chaining
if (foo?.bar?.baz) {
    // ...
}

// Nullish Coalescing
let x = foo ?? bar()
```

**Comment by efueger** [comment]
Hey @rdadoune - can you drop a Code Climate link to one of your files showing the parsing error? help@codeclimate.com
Thanks!

**Comment by rdadoune** [comment]
@efueger sure, does this work https://codeclimate.com/repos/5303f5366956801740003195/app/assets/typescripts/packs/v10/premium/phone_presentation/ducks/selectors/demographicsSelector.ts

**Comment by efueger** [comment]
updated here: https://github.com/codeclimate/codeclimate-eslint/pull/494/files 👍

**Pull request closed without merging**
