### PR TITLE
Add eslint-plugin-compat to supported plugins

### PR DESCRIPTION
**Pull request by athal7**

### CODE REVIEW

**Comment by athal7** [comment]
I can’t remember sorry @dkniffin

**Comment by dkniffin** [comment]
@athal7 would you mind re-opening it?

cc @larkinscott since you're assigned
cc @dantevvp and @noelia-lencina since you seem to be more active in here lately.

**Comment by dkniffin** [comment]
Also, I'd like to see this in previous versions of eslint. I'm currently running eslint-5

**Comment by athal7** [comment]
I’m not able to reopen, maybe worth starting a new one

**Comment by dkniffin** [comment]
Done: https://github.com/codeclimate/codeclimate-eslint/pull/597

**Pull request closed without merging**
