### PR TITLE
fix: add support for babel-plugin-react-generate-property

### PR DESCRIPTION
**Pull request by rachelslurs**
Sorry, I think this is our last one. :grimacing: :pray: 

Thank you so much!

### CODE REVIEW

**Comment by rachelslurs** [comment]
@noelia-lencina any chance we can get this in soon? I'm getting fairly nervous not having our lint checks running.

**Comment by efueger** [comment]
Hi @rachelslurs - checking on this. Will be in touch soon! Thanks for the PR.

**Review by noelia-lencina — APPROVED** [review]

**Comment by noelia-lencina** [comment]
@rachelslurs Sorry for the delay, this should be available now. Thanks!

**Comment by rachelslurs** [comment]
@noelia-lencina @efueger thank you, all!

**Pull request merged**
