### PR TITLE
support @br/eslint-plugin-laws-of-the-game

### PR DESCRIPTION
**Pull request by alxndr**
[`@br/eslint-plugin-laws-of-the-game`](https://www.npmjs.com/package/@br/eslint-plugin-laws-of-the-game) is a couple rules which are important to the Front-End team at @bleacherreport — https://github.com/bleacherreport/eslint-plugin-laws-of-the-game

### CODE REVIEW

**Comment by efueger** [comment]
Hi @alxndr - thanks for the PR. I've added this to our queue to review. 👍

Cheers,
Emily, Code Climate Support

**Comment by alxndr** [comment]
Ping, any ETA on this?

(FWIW I will most likely be unresponsive 2/27–3/7.)

**Comment by alxndr** [comment]
Ping...

**Comment by efueger** [comment]
Oh... so sorry that we dropped this.
- I'll close for now, but let me know if this would be helpful.

**Pull request closed without merging**
