### PR TITLE
updated version to 1.1.0 for eslint-plugin-xogroup

### PR DESCRIPTION
**Pull request by lamchakchan**
## Context

Updating an existing plugin `eslint-plugin-xogroup` to the most current version @ `1.1.0`

## Changes

* `package.json`
* `yarn.lock`

### CODE REVIEW

**Comment by lamchakchan** [comment]
Just FYI, I ran into this issue running `bin/yarn`.  The process did update the `yarn.lock` file but that was it.

```
> bin/yarn upgrade eslint-plugin-xogroup
yarn upgrade v0.22.0-20170305.2241
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "eslint-config-airbnb@11.2.0" has incorrect peer dependency "eslint-plugin-import@^1.16.0".
warning "eslint-config-airbnb-base@7.2.0" has incorrect peer dependency "eslint-plugin-import@^1.16.0".
warning "eslint-plugin-prettier@2.0.0" has unmet peer dependency "prettier@>= 0.11.0".
[4/4] Rebuilding all packages...
success Saved lockfile.
success Saved 1 new dependency.
└─ eslint-plugin-xogroup@1.1.0
Done in 16.76s.
error An unexpected error occurred: "EACCES: permission denied, open '/tmp/v8-compile-cache/5.1.281.81/zSusrzSsharezSyarnzSbinzSyarn.js.LOCK'".
info If you think this is a bug, please open a bug report with the information provided in "/usr/src/app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/upgrade for documentation about this command.
```

**Comment by GordonDiggs** [comment]
Hey @lamchakchan ESLint 3 is now in the master branch - can you change this PR to be against master?

**Comment by maxjacobson** [comment]
@lamchakchan Thanks for the head's up about yarn. This is fixed in #189, I just need to merge that.

**Comment by lamchakchan** [comment]
@GordonDiggs will do.

**Pull request closed without merging**
