### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by benmccann**

### CODE REVIEW

**Comment by dblandin** [comment]
@benmccann Thanks!

**Comment by benmccann** [comment]
Thanks Devon! Do I need to wait some amount of time before this change will be available on the Code Climate servers?

**Comment by dblandin** [comment]
Shouldn't take too long but yes, I'll need to push the update through our systems before it's available on codeclimate.com. I'll ping you here when that's done 👍

**Comment by dblandin** [comment]
@benmccann Should be all set!

**Comment by benmccann** [comment]
Thank you!!

**Pull request merged**
