### PR TITLE
Update @typescript-eslint to the latest version

### PR DESCRIPTION
**Pull request by Loremaster**
Hey,

I updated @typescript-eslint to the newest version. Will appreciate if you can merge it!

### CODE REVIEW

**Comment by Loremaster** [comment]
Hey @fede-moya, is it possible to provide an update on this?

**Comment by fede-moya** [comment]
@Loremaster hey there ! Thanks for your contribution I will be checking it now.

**Review by fede-moya — APPROVED** [review]

**Comment by Loremaster** [comment]
@fede-moya appreciate it, thank you!

**Comment by fede-moya** [comment]
@Loremaster released ! 👍🏼

**Pull request merged**
