### PR TITLE
Update eslint to 4.15.0

### PR DESCRIPTION
**Pull request by krzysiek1507**

### CODE REVIEW

**Comment by krzysiek1507** [comment]
ping @chrishulton

**Comment by chrishulton** [comment]
Thanks, this looks good to me.

**Comment by krzysiek1507** [comment]
Thanks! @chrishulton Do you know when Codeclimate will update it?

**Comment by chrishulton** [comment]
Hi, this change is now included in the `channel/eslint-4` branch on Code Climate.  You may need to run `codeclimate engines:install` to pick up the update if you are using the CLI.

**Comment by krzysiek1507** [comment]
Hi @chrishulton I mean https://codeclimate.com Docs say that there is [4.7.1](https://docs.codeclimate.com/docs/eslint).

**Comment by chrishulton** [comment]
Ah, we just need to update those docs now.  The version should be 4.15.0 for eslint-4 with this change included.  Thanks!

**Comment by krzysiek1507** [comment]
Nice! Thanks!

**Pull request merged**
