### PR TITLE
Add eslint-plugin-react-hooks to channel/eslint-4

### PR DESCRIPTION
**Pull request by turbobeast**
* adds `"eslint-plugin-react-hooks"` to `package.json`
* adds `"eslint-plugin-react-hooks"` to `yarn.lock`

### CODE REVIEW

**Comment by efueger** [comment]
requested by user via hello@

**Comment by turbobeast** [comment]
Is there something i need to do to get CI to run.. or is it started manually?

**Comment by filipesperandio** [comment]
@turbobeast We need to move to Circle 2. I am on it today.

**Comment by filipesperandio** [comment]
@turbobeast  Could you rebase with latest from `channel/eslint-4`? I've updated CI configs.

**Comment by turbobeast** [comment]
I think this is ready to go.

**Pull request merged**
