### PR TITLE
[eslint-4] Update eslint-plugin-jsx-a11y (6.0.3)

### PR DESCRIPTION
**Pull request by krzysiek1507**

### CODE REVIEW

**Comment by krzysiek1507** [comment]
Hi @dblandin Can I ask you to merge it? :)

**Comment by krzysiek1507** [comment]
Note: It is required to make `eslint-4` working.

```
ESLint is running with the /usr/local/node_modules/babel-eslint/lib/index.js parser.
Ignoring the following rules that rely on module resolution:

* import/extensions
* import/no-unresolved
* import/no-extraneous-dependencies
* import/no-named-as-default
* import/no-absolute-path
* import/no-duplicates
* import/no-named-as-default-member
/usr/local/node_modules/jsx-ast-utils/lib/values/expressions/index.js:173
    throw new Error(errorMessage(type));
    ^

Error: The prop value with an expression type of BindExpression could not be resolved.
  Please file issue to get this fixed immediately.
    at Object.extract [as JSXExpressionContainer] (/usr/local/node_modules/jsx-ast-utils/lib/values/expressions/index.js:173:11)
    at getValue (/usr/local/node_modules/jsx-ast-utils/lib/values/index.js:48:27)
    at extractValue (/usr/local/node_modules/jsx-ast-utils/lib/getPropValue.js:24:12)
    at getPropValue (/usr/local/node_modules/jsx-ast-utils/lib/getPropValue.js:41:10)
    at /usr/local/node_modules/eslint-plugin-jsx-a11y/lib/rules/no-static-element-interactions.js:76:95
    at Array.some (native)
    at JSXOpeningElement (/usr/local/node_modules/eslint-plugin-jsx-a11y/lib/rules/no-static-element-interactions.js:75:52)
    at listeners.(anonymous function).forEach.listener (/usr/local/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (native)
    at Object.emit (/usr/local/node_modules/eslint/lib/util/safe-emitter.js:47:38)
```

**Comment by wilson** [comment]
Looks good to me. Once new images have been built and deployed, this will be on the `eslint-4` channel.

Thanks for the contribution.

**Comment by krzysiek1507** [comment]
Thanks! It works!

**Comment by ykzts** [comment]
oops, breaking change...

**Pull request merged**
