### PR TITLE
Update eslint-config-will-robinson

### PR DESCRIPTION
**Pull request by jacksonrayhamilton**
Hello,

This plugin has been updated to use new rules only available in ESLint 5.  Will you please allow us to use the latest version on this channel?

Thanks,
Jackson

### CODE REVIEW

**Comment by jacksonrayhamilton** [comment]
bump @maxjacobson @eutopian

**Comment by jacksonrayhamilton** [comment]
Thanks @filipesperandio

**Comment by filipesperandio** [comment]
Haven't made prod yet, but is on the pipeline.

**Comment by jacksonrayhamilton** [comment]
@filipesperandio has this made it to prod?  If not will you please ping me when it does?

**Comment by filipesperandio** [comment]
Will do 👍. Sorry for the delay.

**Comment by filipesperandio** [comment]
@jacksonrayhamilton It is live! 🎉

**Pull request merged**
