### PR TITLE
added eslint-plugin-xogroup plugin

### PR DESCRIPTION
**Pull request by lamchakchan**
**Context**

As a customer of Code Climate, we would like to extend the `codeclimiate-eslint` engine to accept our custom `eslint-plugin-xogroup` plugin.  We have many JS projects analyzed under the Code Climate toolset.  It is at the point where we need a single source of truth for our rules definition which `eslint` supports.  Since Code Climate does not extensibly allow for custom configs for plugins with `eslint` support, our Code Climate rep informed us we were free to make a PR against this engine to get our plugin added.  Our `eslint-plugin-xogroup` plugin has been NSP scanned.  Please accept that as security compliant.

**Changes**

- Added `eslint-plugin-xogroup` reference to package.json
- Added `eslint-plugin-xogroup` reference to yarn.lock

### CODE REVIEW

**Comment by lamchakchan** [comment]
Hello @maxjacobson.  While trying to follow the [CONTRIBUTING.md](https://github.com/codeclimate/codeclimate-eslint/blob/channel/eslint-3/CONTRIBUTING.md), the commands for `bin/yarn add <package>` failed for me.  I ended up installing the references locally outside of Docker.  

**My Docker version**

```
➜  codeclimate-eslint git:(add-eslint-plugin-xogroup) docker --version
Docker version 1.7.1, build 786b29d
```

**Error**

```
➜  codeclimate-eslint git:(add-eslint-plugin-xogroup) bin/yarn add eslint-plugin-xogroup
yarn add v0.20.0-20170126.2327
[1/4] Resolving packages...
[2/4] Fetching packages...
error Could not write file "/usr/src/app/yarn-error.log": "EACCES: permission denied, open '/usr/src/app/yarn-error.log'"
error An unexpected error occurred: "EACCES: permission denied, unlink '/usr/src/app/node_modules/.yarn-integrity'".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
➜  codeclimate-eslint git:(add-eslint-plugin-xogroup) sudo bin/yarn add eslint-plugin-xogroup
yarn add v0.20.0-20170126.2327
[1/4] Resolving packages...
[2/4] Fetching packages...
error Could not write file "/usr/src/app/yarn-error.log": "EACCES: permission denied, open '/usr/src/app/yarn-error.log'"
error An unexpected error occurred: "EACCES: permission denied, unlink '/usr/src/app/node_modules/.yarn-integrity'".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by maxjacobson** [comment]
@lamchakchan sorry to hear that, but thanks for trying. The patch looks the same as it would if it were run inside the docker container, so I'm happy to merge this in shortly. Thanks for the PR :)

**Comment by maxjacobson** [comment]
This is live now :)

**Comment by lamchakchan** [comment]
Thank you!

**Pull request merged**
