### PR TITLE
add hapi config support

### PR DESCRIPTION
**Pull request by idoshamun**

### CODE REVIEW

**Comment by pbrisbin** [comment]
Thanks @idoshamun! cc/ @ABaldwinHunter

**Comment by ABaldwinHunter** [comment]
@idoshamun Thanks for the work here! LGTM

**Comment by ABaldwinHunter** [comment]
@idoshamun This eslint-2 change is live now. Thanks again!

**Comment by idoshamun** [comment]
Glad to hear it!

**Pull request merged**
