### PR TITLE
output some perf timing to stderr

### PR DESCRIPTION
**Pull request by wfleming**
This is part of https://trello.com/c/93amREzt/751-eslint-performance-issue-discrepency-between-local-and-bbg

@GordonDiggs does this kind of look like what you were thinking?

Output looks like:

```
eslint.timing.engineConfig: 0s
eslint.timing.fileWalk: 0.003s
eslint.timing.cliInit: 0s
eslint.timing.cliRun: 0.001s
eslint.timing.resultsOutput: 0s
```

### CODE REVIEW

**Comment by GordonDiggs** [comment]
Yep generally the concept looks good! What do you think of using node's `console.time`? https://nodejs.org/api/console.html#console_console_time_label

**Comment by GordonDiggs** [comment]
Not sure if it's easy/possible to direct that output to stderr though

**Comment by wfleming** [comment]
I think `console.time` outputs to stdout, not stderr. Couldn't see a simple way to redirect it, so i just wrote it myself.

**Comment by GordonDiggs** [comment]
LGTM

**Pull request merged**
