### PR TITLE
Update eslint-config-will-robinson

### PR DESCRIPTION
**Pull request by jacksonrayhamilton**
Hello,

This plugin has been updated to use new rules only available in ESLint 7. Will you please allow us to use the latest version on this channel?

Thanks,
Jackson

### CODE REVIEW

**Comment by jacksonrayhamilton** [comment]
@fede-moya can we get this reviewed/merged please?

**Comment by fede-moya** [comment]
@jacksonrayhamilton Thank you very much for your contribution. Sorry for this taking us so long, I will review it this week and most likely, considering your changes, also merge it and release it before the end of the week. Sounds good ?

**Review by fede-moya — APPROVED** [review]

**Comment by fede-moya** [comment]
@jacksonrayhamilton Sorry for the delayed. A new release is in the queue now, I will notify you after the release is done !. Regards 👋🏼

**Comment by fede-moya** [comment]
@jacksonrayhamilton Released ! 👋🏼

**Pull request merged**
