### PR TITLE
Add react-perf plugin support

### PR DESCRIPTION
**Pull request by MosheZemah**
Adding support for [react-perf plugin](https://www.npmjs.com/package/eslint-plugin-react-perf)

### CODE REVIEW

**Comment by MosheZemah** [comment]
@fede-moya can you approve please?

**Comment by fede-moya** [comment]
@MosheZemah hey ! How are you ?

**Comment by fede-moya** [comment]
@MosheZemah Hi! 👋🏼

**Comment by MosheZemah** [comment]
> @MosheZemah Hi! 👋🏼
> 
> Could you tell me first if you are using an specific channel like `eslint-7` or another one ?

I've updated our channel to be eslint-7. Thanks

**Comment by fede-moya** [comment]
@MosheZemah great, then could you open you pr against [channel/eslint-7](https://github.com/codeclimate/codeclimate-eslint/tree/channel/eslint-7) instead of master please ? I tried to do it myself but your branch it's based on master too so you will need to apply those changes over a branch checked out from `channel/eslint-7`.

**Comment by MosheZemah** [comment]
> @MosheZemah great, then could you open you pr against [channel/eslint-7](https://github.com/codeclimate/codeclimate-eslint/tree/channel/eslint-7) instead of master please ? I tried to do it myself but your branch it's based on master too so you will need to apply those changes over a branch checked out from `channel/eslint-7`.

Hi, created a new PR - https://github.com/codeclimate/codeclimate-eslint/pull/525
Closing this one

**Pull request closed without merging**
