### PR TITLE
add eslint-plugin-ember

### PR DESCRIPTION
**Pull request by akatov**

### CODE REVIEW

**Comment by akatov** [comment]
@wilson, @maxjacobson rebased and ready to merge...

**Comment by dblandin** [comment]
@akatov Thanks! Will get this rolled out :+1:

**Comment by akatov** [comment]
@dblandin Thanks for merging! How long does it usually take for these changes to go into production?

**Comment by dblandin** [comment]
Hey @akatov,

This should be rolled out to production now. We're usually a little faster at getting these updates out once merged but it has been a busy day. Thanks for your patience!

**Pull request merged**
